### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by nightwolf93** [Dionakov/CrohEmu#1]
Salut, je viens de tombé sur ton projet, je suis actuellement en train des choses dans mon coin également, donc pour me contacté voici mon Discord : Nightwolf#8268 :)

**Comment by Dionakov** [comment]
Dionakov#3783
je t'ai ajouté normalement :)

**Comment by nightwolf93** [comment]
Yep j'ai vu ça, je suis connecté au boulot là par texte, si tu as le temps ce soir je suis dispo vocal :)
